### ISSUE TITLE
Corail Pillar update is breaking Pillar Extension for BOP.

### ISSUE THREAD

**Issue by Zarepheth** [Corail31/corail-pillar#3]
The Corail Pillar Extension for Biomes O'Plenty now fails when using the most recent version of Corail Pillar. The failure occurs as the game is loading.

Minecraft: 1.12
Forge: 14.21.1.2395 (2387 also flagged an error with the extension mod)
Corail Pillar: 2.1.0
Pillar Extension for BOP: 2.1.0

The Pillar Extension for Quark does not fail during game startup.

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Corail Pillar - Biomes O'Plenty Extension (pillar_extension_biomesoplenty)
Caused by: java.lang.NullPointerException
	at biomesoplenty.common.block.BlockBOPLog.getFireSpreadSpeed(BlockBOPLog.java:143)
	at corail_pillar.core.TypePillar.<init>(TypePillar.java:53)
	at corail_pillar.core.PillarManager.addPillar(PillarManager.java:44)
	at corail_pillar.core.PillarManager.addPillar(PillarManager.java:32)
	at pillar_extension_biomesoplenty.Main.preInit(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:628)
	...
```
[Log File on paste.ee](https://paste.ee/p/dXYFm)

**Comment by Corail31** [comment]
oh well i'll correct this, thanks for report !

**Comment by Corail31** [comment]
fixed in release 2.1.1

**Comment by EmanYm** [comment]
This is still occurring in 3.0.0

>[23:20:51] [Server thread/FATAL] [FML]: The mod pillar_extension_biomesoplenty does not wish to run in Minecraft version Minecraft 1.12. You will have to remove it to play.
[23:20:51] [Server thread/FATAL] [FML]: Wrong Minecraft version for pillar_extension_biomesoplenty

> net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for pillar_extension_biomesoplenty
Wrong Minecraft Versions!
Mod: pillar_extension_biomesoplenty
Location: /data/service11610/data/service_item_538179/mods/corail_pillar_extension_biomesoplenty-3.0.0.jar
Expected: [1.8.9,1.11.2]
Current: Minecraft 1.12
at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:244) ~[Loader.class:?]
at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547) ~[Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) ~[FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[nx.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

SpongeForge-1.12-2397-7.0.0-Beta-2474
BiomesoPlenty-1.12-7.0.0.2289-universal
corail-pillar-3.0.0-1.12.0
corail_pillar_extension_biomesoplenty-3.0.0

**Comment by Corail31** [comment]
https://minecraft.curseforge.com/projects/corail-pillar-extension-biomes-oplenty/files/2452962
Extension have always 2 versions : one for 1.12 (and above) and one for 1.11.2 (and below).
So you must use the 1.12 version of the extension : 
filename : corail_pillar_extension_biomesoplenty-3.0.0-**1.12**
https://minecraft.curseforge.com/projects/corail-pillar-extension-biomes-oplenty/files/2452962

**Comment by EmanYm** [comment]
I ALWAYS filter by the version I want to use.
Three days ago (give or take a day) when I downloaded it, the version I mentioned above is what was given to me.
I downloaded it just now and I got a completely different file from the exact same button.

**Comment by Corail31** [comment]
So all is working ? :)

**Comment by Corail31** [comment]
You're right by the way ;)
Corail Pillar - Extension BOP 3.0.0 for 1.12 | 29.48 KB | 3 days ago | 1.12 | 1 | Deleted
no luck for you, you were the first to download it (and it was the wrong file)

**Comment by EmanYm** [comment]
I have not yet restarted the server since changing files, but I am confident it will work.  I will update this issue when I restart.

**Comment by Zarepheth** [comment]
The last few versions of the Pillar Extensions for both BOP and Quark have been working fine for me.

On a side note, where do we file requests for Curse itself? I've set my Curse shortcut to open the mods, filtered to Minecraft 1.12 and sorted by Most Recently Updated -- but, any file updates, to any version of the mod will cause the mod to sort closer to the top. So, someone updating their MC v1.7 edition of the mod can cause their mod to show up at the top of my MC 1.12 filter, even though the MC 1.12 version hasn't been updated for a month or more.

**Comment by Corail31** [comment]
No idea, sorry, perhaps ask to [Torhal](https://minecraft.curseforge.com/members/Torhal)
